import type { FileTypeCategory } from '@shared/ipc';

/** Порядок вывода категорий типов файлов в подкатегории Sidebar. */
export const FILE_TYPE_CATEGORIES: FileTypeCategory[] = [
  'Documents',
  'Images',
  'Video',
  'Audio',
  'Archives',
  'Installers',
  'Code',
  'System',
  'Other',
];

const CATEGORY_BY_EXTENSION: Readonly<Record<string, FileTypeCategory>> = {
  // Images
  png: 'Images',
  jpg: 'Images',
  jpeg: 'Images',
  gif: 'Images',
  bmp: 'Images',
  webp: 'Images',
  svg: 'Images',
  tiff: 'Images',
  tif: 'Images',
  ico: 'Images',
  heic: 'Images',
  avif: 'Images',
  // Documents
  pdf: 'Documents',
  doc: 'Documents',
  docx: 'Documents',
  xls: 'Documents',
  xlsx: 'Documents',
  ppt: 'Documents',
  pptx: 'Documents',
  odt: 'Documents',
  ods: 'Documents',
  odp: 'Documents',
  rtf: 'Documents',
  txt: 'Documents',
  md: 'Documents',
  csv: 'Documents',
  tsv: 'Documents',
  epub: 'Documents',
  log: 'Documents',
  // Video
  mp4: 'Video',
  mkv: 'Video',
  avi: 'Video',
  mov: 'Video',
  wmv: 'Video',
  flv: 'Video',
  webm: 'Video',
  m4v: 'Video',
  mpg: 'Video',
  mpeg: 'Video',
  m2ts: 'Video',
  // Audio
  mp3: 'Audio',
  wav: 'Audio',
  flac: 'Audio',
  aac: 'Audio',
  ogg: 'Audio',
  oga: 'Audio',
  opus: 'Audio',
  m4a: 'Audio',
  wma: 'Audio',
  mid: 'Audio',
  midi: 'Audio',
  // Archives
  zip: 'Archives',
  rar: 'Archives',
  '7z': 'Archives',
  tar: 'Archives',
  gz: 'Archives',
  bz2: 'Archives',
  xz: 'Archives',
  zst: 'Archives',
  iso: 'Archives',
  cab: 'Archives',
  arj: 'Archives',
  lz: 'Archives',
  lzma: 'Archives',
  // Installers
  exe: 'Installers',
  msi: 'Installers',
  msp: 'Installers',
  msix: 'Installers',
  appx: 'Installers',
  // Code
  js: 'Code',
  mjs: 'Code',
  cjs: 'Code',
  ts: 'Code',
  tsx: 'Code',
  jsx: 'Code',
  c: 'Code',
  h: 'Code',
  cpp: 'Code',
  hpp: 'Code',
  cc: 'Code',
  cxx: 'Code',
  cs: 'Code',
  java: 'Code',
  py: 'Code',
  rb: 'Code',
  go: 'Code',
  rs: 'Code',
  swift: 'Code',
  kt: 'Code',
  php: 'Code',
  sh: 'Code',
  pl: 'Code',
  lua: 'Code',
  sql: 'Code',
  html: 'Code',
  htm: 'Code',
  css: 'Code',
  scss: 'Code',
  less: 'Code',
  xaml: 'Code',
  json: 'Code',
  xml: 'Code',
  yaml: 'Code',
  yml: 'Code',
  toml: 'Code',
  ini: 'Code',
  cfg: 'Code',
  conf: 'Code',
  graphql: 'Code',
  vue: 'Code',
  svelte: 'Code',
  // System
  dll: 'System',
  sys: 'System',
  drv: 'System',
  vxd: 'System',
  ocx: 'System',
  mui: 'System',
  nls: 'System',
  pdb: 'System',
  manifest: 'System',
};

export function classifyFileTypeCategory(fileName: string): FileTypeCategory {
  const name = fileName.trim();
  if (name === '' || name === '.') {
    return 'Other';
  }
  const dotIndex = name.lastIndexOf('.');
  if (dotIndex <= 0) {
    return 'Other';
  }
  const extension = name.slice(dotIndex + 1).toLowerCase();
  return CATEGORY_BY_EXTENSION[extension] ?? 'Other';
}